name: Publish to crates.io

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: crates-io
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
